name: Kotlin Test

on:
  push:
    paths:
      - 'mars_rover_kotlin/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change directory to specific folder
      run: cd mars_rover_kotlin

    - name: Set up JDK
      uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: 'adopt-openjdk-11'
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
