name: Playground Test

on:
  push:
    paths:
      - 'mars_rover_kotlin/**'

jobs:
  kotlin-test:
    if: contains(github.event.commits.*.modified, 'mars_rover_kotlin/**')
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Build with Gradle
      run: |
        cd mars_rover_kotlin
        ./gradlew build
    
    - name: Run tests
      run: |
        cd mars_rover_kotlin
        ./gradlew test
