name: Kotlin Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Change directory to specific folder
      run: cd mars_rover_kotlin
    
    - name: Generate gradle wrapper
      run: gradle wrapper
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
